name: 'Greeter and Printer'
description: 'Run a JAR file, which greets the user and prints the contents of changed files'

inputs:
  name:
    description: 'The account to greet'
    required: True
  changed-files:
    description: 'List of changed files'
    required: True

outputs:
  greeting:
    description: 'The greeting to the person, who opened the pull request'
  files-contents:
    description: 'The contents of changed files'
    
runs:
  using: 'node16'
  main: 'main.js'
