name: 'Greeter'
description: 'Run a JAR file, which greets the user'

inputs:
  name:
    description: 'The account to greet'

outputs:
  jar-output:
    description: 'The output of the JAR file'
    
runs:
  using: 'node16'
  main: 'main.js'
